export const todaysAppointments = [
    {
        id: 1,
        time: "09:00 AM",
        patientName: "John Doe",
        age: 42,
        gender: "Male",
        reason: "Follow-up for diabetes",
        contact: "+64 21 123 4567",
        status: "Upcoming",
        notes: "Last visit: blood sugar slightly elevated",
    },
    {
        id: 2,
        time: "10:30 AM",
        patientName: "Jane Smith",
        age: 34,
        gender: "Female",
        reason: "Migraine consultation",
        contact: "+64 27 555 8888",
        status: "Upcoming",
        notes: "Responded well to medication last visit",
    },
    {
        id: 3,
        time: "11:15 AM",
        patientName: "David Johnson",
        age: 57,
        gender: "Male",
        reason: "Routine check-up",
        contact: "+64 22 789 3333",
        status: "Pending",
        notes: "Needs lab test follow-up",
    },
    {
        id: 4,
        time: "11:15 AM",
        patientName: "David ",
        age: 57,
        gender: "Male",
        reason: "Routine check-up",
        contact: "+64 22 789 3333",
        status: "Pending",
        notes: "Needs lab test follow-up",
    },
    {
        id: 5,
        time: "11:15 AM",
        patientName: " Johnson",
        age: 57,
        gender: "Male",
        reason: "Routine check-up",
        contact: "+64 22 789 3333",
        status: "Pending",
        notes: "Needs lab test follow-up",
    },
];
